version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - model
  model:
    image: python:3.9-slim
    command: /bin/bash -c "pip install torch torchvision torchaudio && tail -f /dev/null"
